name: brew test-bot

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v14.6
        with:
          files: |
             **.rb
      - name: Audit changed formulae
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            FORMULA=$(basename $file .rb)
            brew audit $FORMULA
          done
